// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA67aLXrREweGMiUcsJGYW6qCnEUxxnkjQ',
    appId: '1:238516070872:web:0d6c00d6e2cece75c86aad',
    messagingSenderId: '238516070872',
    projectId: 'mungle-1aa92',
    authDomain: 'mungle-1aa92.firebaseapp.com',
    storageBucket: 'mungle-1aa92.firebasestorage.app',
    measurementId: 'G-YN6MDLDEG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOWlXQ8GCvAX_P4hKQRNprT9apejw2-DI',
    appId: '1:238516070872:android:d2fa230d3a055672c86aad',
    messagingSenderId: '238516070872',
    projectId: 'mungle-1aa92',
    storageBucket: 'mungle-1aa92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoeIA0TAex0A3pfdhfo1Zj3-QUUJSSrVM',
    appId: '1:238516070872:ios:f52bd8b52ad9bc31c86aad',
    messagingSenderId: '238516070872',
    projectId: 'mungle-1aa92',
    storageBucket: 'mungle-1aa92.firebasestorage.app',
    iosClientId: '238516070872-j7034viue4f61k2m0lng6o3tkfbr012k.apps.googleusercontent.com',
    iosBundleId: 'com.example.mungle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoeIA0TAex0A3pfdhfo1Zj3-QUUJSSrVM',
    appId: '1:238516070872:ios:f52bd8b52ad9bc31c86aad',
    messagingSenderId: '238516070872',
    projectId: 'mungle-1aa92',
    storageBucket: 'mungle-1aa92.firebasestorage.app',
    iosClientId: '238516070872-j7034viue4f61k2m0lng6o3tkfbr012k.apps.googleusercontent.com',
    iosBundleId: 'com.example.mungle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA67aLXrREweGMiUcsJGYW6qCnEUxxnkjQ',
    appId: '1:238516070872:web:9aea15cadf5e00c8c86aad',
    messagingSenderId: '238516070872',
    projectId: 'mungle-1aa92',
    authDomain: 'mungle-1aa92.firebaseapp.com',
    storageBucket: 'mungle-1aa92.firebasestorage.app',
    measurementId: 'G-BCQY9GVC7J',
  );
}
